# Generated by Django 4.1 on 2022-08-27 11:18

from django.db import migrations, models
import django.db.models.deletion
import main.storage
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=main.storage.CustomStorage(), upload_to='documents/', validators=[main.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[('1', 'IT'), ('2', 'HR'), ('3', 'Finance')], max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document')),
            ],
        ),
    ]
