# Generated by Django 4.1 on 2022-08-27 11:59

from django.db import migrations, models
import main.validators
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='equevotask'), upload_to='documents/', validators=[main.validators.validate_file_extension]),
        ),
    ]
