# Generated by Django 4.1 on 2022-08-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.document'),
        ),
    ]
